### ISSUE TITLE
Python exception when trying to cut simple wing

### ISSUE THREAD

**Issue by andir** [Shkolik/Foamcut#6]
Thanks for this great workbench! I've been looking for something like this for a while. Perhaps this will be a good excuse to actually build a CNC hot wire! :-)

Unfortunately I've come across an error when trying to create G-Code for a quickly drafted together example. I've attached the project file. The workbench revision is ee4c2da60159ee4ddd9add6bb41bfa23cf745887.

After creating a path and hitting the G-Code button I'm getting the following error:

```
23:24:23  Running the Python command 'MakeGcode' failed:
Traceback (most recent call last):
  File ".../.local/share/FreeCAD/Mod/FoamCut/./Postprocess.py", line 305, in Activated
    self.makeGCODE(routes, config)
  File ".../local/share/FreeCAD/Mod/FoamCut/./Postprocess.py", line 226, in makeGCODE
    point_l = route.Offset_L[point_index]
              ~~~~~~~~~~~~~~^^^^^^^^^^^^^

list index out of range


```

![image](https://github.com/user-attachments/assets/06e39e5c-70e5-4a36-9741-42e4fa427b86)

[FoamCutterExample.zip](https://github.com/user-attachments/files/17909584/FoamCutterExample.zip)

**Comment by Shkolik** [comment]
Thank you for your attention to details. I found what cause the issue and fixed it for upcoming release. If you want to get this update right away switch to release_0.1.5 branch. You will need to force recalculate your Route or create a new one.

Actually I missed this issue because it's not common scenario to cut something without kerf compensation. If you change Compensation strategy to Uniform and Compensation direction to Reversed it will work even without a fix. 

![image](https://github.com/user-attachments/assets/8a303228-b977-4519-9453-c628fcbf4947)

One more remark to your test file - it's all good in virtual environment, but in real life you will not be able to cut this wing as it designed. Foam isn't very ridged or uniform material and warps a bit with a heat, so it's a good practice to not cut trailing edge to a point. I usually leave at least 1mm thickness there. But, probably, with a little bit more kerf compensation and a lot of luck it's possible :)

**Comment by andir** [comment]
Thank you for the quick fix! I'm aware my wing wouldn't be practical. I just drafted one manually to test the workbench and to understand how it works. For a proper wing I'd import a proper profile.
